apiVersion: v1

kind: Pod

metadata:

  name: udacity-project

  labels:

    purpose: udacity-project

spec:

  containers:

  - name: udacity-project

    image: ololade/udacity-project
    
    ports:
    - name: web
      containerPort: 80
      

    command: ["printenv"]

  restartPolicy: Always
